### ISSUE TITLE
show affix icons from wowhead

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#2]
like here: https://wowaffixes.info/#

**Comment by Kaeseknacker** [comment]
https://www.wowhead.com/tooltips

Something like this should work:

Header
```HTML
<script>const whTooltips = {colorLinks: true, iconizeLinks: true, renameLinks: true};</script>
<script src="https://wow.zamimg.com/js/tooltips.js"></script>
```
Body
```HTML
<a href="https://en.wowhead.com/affix=10/"><span>Fortified</span></a>
```

**Comment by derwhite** [comment]
It's a little better now, but i want icons instead of `<span>TEXT</span>` 
i did a quick look  @Kaeseknacker 

>  like here: https://wowaffixes.info/#

 and didn't understand how they did this.
In my mind, i would write something like `<img scr="URL">` to get an icon/image on my site.... so i'm a bit confused.

**Comment by Kaeseknacker** [comment]
Yes, they use their own icons:

HTML:
```HTML
<a href="[https://en.wowhead.com/affix=10/](view-source:https://en.wowhead.com/affix=10/)" class="affixes affixes-10"></a><br />
```
CSS:
```CSS
.affixes-10:before { background-image:url('../images/fortified.jpg');  }

.affixes:before {
  border-radius:50%;
  -webkit-border-radius: 50%;
  padding-right: 20px;
  content:' ';
  background-size: 20px;
  background-repeat: no-repeat;
  margin-right: 10px;
}

.affixes {
  float: left;
}
```
